### ISSUE TITLE
argument is missing in step function

### ISSUE THREAD

**Issue by LucaNicoliYT88** [timtroendle/simple-simple#1]
Hi Tim,

heating_cooling_power argument is missing in step function.

https://github.com/timtroendle/simple-simple/blob/e7ff8f5868d28cd4b3f2ec0b91e7de9b4fcf49c9/simplesimple/building.py#L33

**Comment by timtroendle** [comment]
Hi Luca, it is missing deliberately. The heating or cooling power is a dependent variable: it depends on the current temperature in the building and the heating/cooling set point. The control system is within the model and decides on the necessary heating or cooling power. If you want to control the power yourself, you would need to change the model. Does that makes sense?
