### ISSUE TITLE
Is output heating power misssing?

### ISSUE THREAD

**Issue by ckohrt** [timtroendle/simple-simple#2]
Hi Tim,
I have just seen your python code here. I would like to use it for predicting my house temperature for 3h ahead to control the heating system. The prediction of the temperature seems to be a good point, but I miss the output heating power the algorithm is using. I could set the max heating power to zero and with the result I could control my heating system based on delta temperature.
You state:
ΦHC, nd, t: cooling or heating power at time t
Where is it?

BTW good work!
Christian

**Comment by timtroendle** [comment]
Hi Christian, happy if this is useful for you. Good catch about the thermal power. I've added it in the commit above. See the commit or the updated usage example in the README and let me know if this does not fix your issue.

**Comment by ckohrt** [comment]
Thanks, perfect to what I have seen in code. I just also tried the https://github.com/architecture-building-systems/RC_BuildingSimulator which is also useful because more things are simulated, like windows etc. On the other hand more complex.... BTW I was able to find it with your comments here with the reference to the standards ...
Cheers
Christian
