### ISSUE TITLE
Heat mass capacity parameter

### ISSUE THREAD

**Issue by TamasIll** [timtroendle/simple-simple#3]
Hi!
I really liked your work, this simple simulator made my life much easier. Can i ask you, how can you determine the value of heat mass capacity? Like is there some rule of thumb to calculate this value? Or do you calculate it from a table of values? Can i ask you to give me some advice, how can i determine this value if i want to simulate a house, if i can literally measure the house dimensions and walls.
Thank you in advance!

**Comment by timtroendle** [comment]
Hi @TamasIll, thanks for reaching out and your kind words. I haven't been working in this field for many years and so I cannot give you any up-to-date sources for parameters, I am afraid. All the best for your modelling work!
